In [19]:
import plotly.plotly as py

In [20]:
import plotly.graph_objs as go

In [21]:
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

In [22]:
init_notebook_mode(connected=True)

In [23]:
import pandas as pd

In [44]:
df=pd.read_csv('countries-of-the-world.zip')
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [76]:
ls

2011_US_AGRI_Exports                Plotly and Cufflink p-1.ipynb
2014_World_GDP                      Untitled1.ipynb
Foodbudget.xlsx                     countries-of-the-world.zip
Geoplot p-1.ipynb                   df1
Geoplot.ipynb                       df2
Pandas Excersise.ipynb              df3
Pandas built in Data viz p-1.ipynb  temp-plot.html
Pandas built in data viz 1.ipynb    world-bank-gdp-ranking.zip
Plotly & Cufflinks 1.ipynb          world-happiness-report-2019.zip

In [110]:
data=dict(
    type='choropleth',
    locations=df['Climate'],
    z=df['Population'],
    colorscale='Blackbody',
    text=df['Population'],
    colorbar={'title':'GDP of the world'}
    
    )

KeyError: 'Climate'

In [111]:
layout=dict(
    title='GDP of the world',
    geo=dict(
    showframe=False,
    projection={'type':'mercator'})
    )

In [112]:
choromap=go.Figure(data=[data],layout=layout)
iplot(choromap)

ValueError:
    Invalid element(s) received for the 'data' property of
        Invalid elements include: [             Country (region)  Ladder  SD of Ladder  Positive affect  \
0                     Finland       1             4             41.0
1                     Denmark       2            13             24.0
2                      Norway       3             8             16.0
3                     Iceland       4             9              3.0
4                 Netherlands       5             1             12.0
5                 Switzerland       6            11             44.0
6                      Sweden       7            18             34.0
7                 New Zealand       8            15             22.0
8                      Canada       9            23             18.0
9                     Austria      10            10             64.0
10                  Australia      11            26             47.0
11                 Costa Rica      12            62              4.0
12                     Israel      13            14            104.0
13                 Luxembourg      14             3             62.0
14             United Kingdom      15            16             52.0
15                    Ireland      16            34             33.0
16                    Germany      17            17             65.0
17                    Belgium      18             7             57.0
18              United States      19            49             35.0
19             Czech Republic      20            20             74.0
20       United Arab Emirates      21            65             43.0
21                      Malta      22            42             83.0
22                     Mexico      23            76              6.0
23                     France      24            19             56.0
24                     Taiwan      25            37             17.0
25                      Chile      26            61             15.0
26                  Guatemala      27           136              8.0
27               Saudi Arabia      28            93             49.0
28                      Qatar      29            86              NaN
29                      Spain      30            21            107.0
..                        ...     ...           ...              ...
126          Congo (Kinshasa)     127            78            125.0
127                      Mali     128            96             48.0
128              Sierra Leone     129           153            139.0
129                 Sri Lanka     130            91             32.0
130                   Myanmar     131            70             45.0
131                      Chad     132           139            136.0
132                   Ukraine     133            69            131.0
133                  Ethiopia     134            38            100.0
134                 Swaziland     135           104             26.0
135                    Uganda     136           148             91.0
136                     Egypt     137            66            146.0
137                    Zambia     138           145             84.0
138                      Togo     139           103            123.0
139                     India     140            41             93.0
140                   Liberia     141           156            103.0
141                   Comoros     142           143             67.0
142                Madagascar     143            77             46.0
143                   Lesotho     144           150             72.0
144                   Burundi     145           138             98.0
145                  Zimbabwe     146           123             63.0
146                     Haiti     147           111            142.0
147                  Botswana     148           125             87.0
148                     Syria     149           137            155.0
149                    Malawi     150           132            129.0
150                     Yemen     151            85            153.0
151                    Rwanda     152            63             54.0
152                  Tanzania     153           122             78.0
153               Afghanistan     154            25            152.0
154  Central African Republic     155           117            132.0
155               South Sudan     156           140            127.0

     Negative affect  Social support  Freedom  Corruption  Generosity  \
0               10.0             2.0      5.0         4.0        47.0
1               26.0             4.0      6.0         3.0        22.0
2               29.0             3.0      3.0         8.0        11.0
3                3.0             1.0      7.0        45.0         3.0
4               25.0            15.0     19.0        12.0         7.0
5               21.0            13.0     11.0         7.0        16.0
6                8.0            25.0     10.0         6.0        17.0
7               12.0             5.0      8.0         5.0         8.0
8               49.0            20.0      9.0        11.0        14.0
9               24.0            31.0     26.0        19.0        25.0
10              37.0             7.0     17.0        13.0         6.0
11              87.0            42.0     16.0        58.0        75.0
12              69.0            38.0     93.0        74.0        24.0
13              19.0            27.0     28.0         9.0        30.0
14              42.0             9.0     63.0        15.0         4.0
15              32.0             6.0     33.0        10.0         9.0
16              30.0            39.0     44.0        17.0        19.0
17              53.0            22.0     53.0        20.0        44.0
18              70.0            37.0     62.0        42.0        12.0
19              22.0            24.0     58.0       121.0       117.0
20              56.0            72.0      4.0         NaN        15.0
21             103.0            16.0     12.0        32.0         5.0
22              40.0            67.0     71.0        87.0       120.0
23              66.0            32.0     69.0        21.0        68.0
24               1.0            48.0    102.0        56.0        56.0
25              78.0            58.0     98.0        99.0        45.0
26              85.0            78.0     25.0        82.0        78.0
27              82.0            62.0     68.0         NaN        82.0
28               NaN             NaN      NaN         NaN         NaN
29             107.0            26.0     95.0        78.0        50.0
..               ...             ...      ...         ...         ...
126             95.0           107.0    125.0       106.0       127.0
127            122.0           112.0    110.0       107.0       138.0
128            149.0           135.0    116.0       112.0        79.0
129             81.0            80.0     55.0       111.0        35.0
130             86.0            96.0     29.0        24.0         1.0
131            151.0           141.0    142.0        80.0       106.0
132             44.0            56.0    141.0       143.0        66.0
133             74.0           119.0    106.0        53.0        99.0
134             57.0           103.0    113.0        41.0       145.0
135            139.0           114.0     99.0        95.0        74.0
136            124.0           118.0    129.0        89.0       132.0
137            128.0           115.0     73.0        69.0        53.0
138            147.0           149.0    120.0        72.0       131.0
139            115.0           142.0     41.0        73.0        65.0
140            146.0           127.0     94.0       126.0       110.0
141            114.0           143.0    148.0        81.0        62.0
142             96.0           128.0    146.0       116.0       136.0
143             64.0            98.0     97.0        59.0       151.0
144            126.0           152.0    135.0        23.0       149.0
145             34.0           110.0     96.0        63.0       141.0
146            119.0           146.0    152.0        48.0        20.0
147             65.0           105.0     60.0        54.0       150.0
148            155.0           154.0    153.0        38.0        69.0
149            110.0           150.0     65.0        64.0       109.0
150             75.0           100.0    147.0        83.0       155.0
151            102.0           144.0     21.0         2.0        90.0
152             50.0           131.0     78.0        34.0        49.0
153            133.0           151.0    155.0       136.0       137.0
154            153.0           155.0    133.0       122.0       113.0
155            152.0           148.0    154.0        61.0        85.0

     Log of GDP\nper capita  Healthy life\nexpectancy
0                      22.0                      27.0
1                      14.0                      23.0
2                       7.0                      12.0
3                      15.0                      13.0
4                      12.0                      18.0
5                       8.0                       4.0
6                      13.0                      17.0
7                      26.0                      14.0
8                      19.0                       8.0
9                      16.0                      15.0
10                     18.0                      10.0
11                     67.0                      28.0
12                     31.0                      11.0
13                      2.0                      16.0
14                     23.0                      24.0
15                      6.0                      20.0
16                     17.0                      25.0
17                     21.0                      26.0
18                     10.0                      39.0
19                     32.0                      31.0
20                      4.0                      60.0
21                     28.0                      19.0
22                     57.0                      46.0
23                     25.0                       5.0
24                      NaN                       NaN
25                     49.0                      30.0
26                     99.0                      85.0
27                     11.0                      74.0
28                      1.0                      43.0
29                     30.0                       3.0
..                      ...                       ...
126                   149.0                     140.0
127                   129.0                     142.0
128                   145.0                     146.0
129                    79.0                      54.0
130                   106.0                     110.0
131                   133.0                     148.0
132                    94.0                      87.0
133                   135.0                     115.0
134                    96.0                       NaN
135                   136.0                     127.0
136                    85.0                     101.0
137                   115.0                     131.0
138                   142.0                     132.0
139                   103.0                     105.0
140                   150.0                     126.0
141                   143.0                     117.0
142                   144.0                     111.0
143                   124.0                     149.0
144                   151.0                     135.0
145                   131.0                     129.0
146                   138.0                     125.0
147                    66.0                     113.0
148                     NaN                     128.0
149                   147.0                     119.0
150                   141.0                     124.0
151                   132.0                     103.0
152                   125.0                     118.0
153                   134.0                     139.0
154                   152.0                     150.0
155                   140.0                     143.0

[156 rows x 11 columns]]

    The 'data' property is a tuple of trace instances
    that may be specified as:
      - A list or tuple of trace instances
        (e.g. [Scatter(...), Bar(...)])
      - A list or tuple of dicts of string/value properties where:
        - The 'type' property specifies the trace type
            One of: ['area', 'bar', 'barpolar', 'box',
                     'candlestick', 'carpet', 'choropleth', 'cone',
                     'contour', 'contourcarpet', 'funnel',
                     'funnelarea', 'heatmap', 'heatmapgl',
                     'histogram', 'histogram2d',
                     'histogram2dcontour', 'isosurface', 'mesh3d',
                     'ohlc', 'parcats', 'parcoords', 'pie',
                     'pointcloud', 'sankey', 'scatter',
                     'scatter3d', 'scattercarpet', 'scattergeo',
                     'scattergl', 'scattermapbox', 'scatterpolar',
                     'scatterpolargl', 'scatterternary', 'splom',
                     'streamtube', 'sunburst', 'surface', 'table',
                     'violin', 'volume', 'waterfall']

        - All remaining properties are passed to the constructor of
          the specified trace type

        (e.g. [{'type': 'scatter', ...}, {'type': 'bar, ...}])

In [101]:
data1=pd.read_csv('world-happiness-report-2019.zip')
data1.head()

,Country (region),Ladder,SD of Ladder,Positive affect,Negative affect,Social support,Freedom,Corruption,Generosity,Log of GDP per capita,Healthy life expectancy
0,Finland,1,4,41.0,10.0,2.0,5.0,4.0,47.0,22.0,27.0
1,Denmark,2,13,24.0,26.0,4.0,6.0,3.0,22.0,14.0,23.0
2,Norway,3,8,16.0,29.0,3.0,3.0,8.0,11.0,7.0,12.0
3,Iceland,4,9,3.0,3.0,1.0,7.0,45.0,3.0,15.0,13.0
4,Netherlands,5,1,12.0,25.0,15.0,19.0,12.0,7.0,12.0,18.0

In [102]:
data2=dict(type='choropleth',
         locations=data1['Country (region)'],
          colorscale='Blackbody',
          text=data1['Ladder'],
          z=data1['Social support'],
         colorbar={'title':'Social support of the world'})

In [103]:
layout1=dict(title='Social support of the world',
             geo=dict(showframe=False,
                      projection={'type':'mercator'}))

In [104]:
choromap=go.Figure(data=[data2],layout=layout1)

In [105]:
iplot(choromap)

In [106]:
pd.read_csv('')

ValueError: ('Multiple files found in compressed zip file %s', "['gdp-csv-.csv', 'gdp-excel-.xls', 'gdp-pdf-.pdf', 'gdp-ppp-csv-.csv', 'gdp-ppp-excel-.xls', 'gdp-ppp-pdf-.pdf']")